apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.237.71.222
  selector:
    app: driver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80