apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  type: ClusterIP
  selector:
    app: namenode
  ports:
    - name: one
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: two
      protocol: TCP
      port: 9870
      targetPort: 9870