apiVersion: v1
kind: Service
metadata:
  name: namenode-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.139.91.253
  selector:
    app: namenode
  ports:
    - protocol: TCP
      port: 9870
      targetPort: 9870
