apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 34.139.141.156
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9000