apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.139.27.45  
  selector:
    app: spark
  ports:
    - protocol: TCP
      port: 2042
      targetPort: 8080