apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  labels:
    app: spark
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spark
        octopusexport: OctopusExport
    spec:
      containers:
        - name: spark
          image: 'docker.io/bitnami/spark:3'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPARK_SSL_ENABLED
              value: 'no'
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: 'no'
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: 'no'
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: 'no'
            - name: SPARK_MODE
              value: master